/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AgentsRouteImport } from './routes/agents'
import { Route as ApprovalsRouteImport } from './routes/approvals'
import { Route as AuditRouteImport } from './routes/audit'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as IntentsRouteImport } from './routes/intents'
import { Route as PlaygroundRouteImport } from './routes/playground'
import { Route as PoliciesRouteImport } from './routes/policies'
import { Route as SecurityRouteImport } from './routes/security'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AgentsRoute = AgentsRouteImport.update({
  id: '/agents',
  path: '/agents',
  getParentRoute: () => rootRouteImport,
} as any)
const ApprovalsRoute = ApprovalsRouteImport.update({
  id: '/approvals',
  path: '/approvals',
  getParentRoute: () => rootRouteImport,
} as any)
const AuditRoute = AuditRouteImport.update({
  id: '/audit',
  path: '/audit',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const IntentsRoute = IntentsRouteImport.update({
  id: '/intents',
  path: '/intents',
  getParentRoute: () => rootRouteImport,
} as any)
const PlaygroundRoute = PlaygroundRouteImport.update({
  id: '/playground',
  path: '/playground',
  getParentRoute: () => rootRouteImport,
} as any)
const PoliciesRoute = PoliciesRouteImport.update({
  id: '/policies',
  path: '/policies',
  getParentRoute: () => rootRouteImport,
} as any)
const SecurityRoute = SecurityRouteImport.update({
  id: '/security',
  path: '/security',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/agents': typeof AgentsRoute
  '/approvals': typeof ApprovalsRoute
  '/audit': typeof AuditRoute
  '/dashboard': typeof DashboardRoute
  '/intents': typeof IntentsRoute
  '/playground': typeof PlaygroundRoute
  '/policies': typeof PoliciesRoute
  '/security': typeof SecurityRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/agents': typeof AgentsRoute
  '/approvals': typeof ApprovalsRoute
  '/audit': typeof AuditRoute
  '/dashboard': typeof DashboardRoute
  '/intents': typeof IntentsRoute
  '/playground': typeof PlaygroundRoute
  '/policies': typeof PoliciesRoute
  '/security': typeof SecurityRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/agents': typeof AgentsRoute
  '/approvals': typeof ApprovalsRoute
  '/audit': typeof AuditRoute
  '/dashboard': typeof DashboardRoute
  '/intents': typeof IntentsRoute
  '/playground': typeof PlaygroundRoute
  '/policies': typeof PoliciesRoute
  '/security': typeof SecurityRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/agents'
    | '/approvals'
    | '/audit'
    | '/dashboard'
    | '/intents'
    | '/playground'
    | '/policies'
    | '/security'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/agents'
    | '/approvals'
    | '/audit'
    | '/dashboard'
    | '/intents'
    | '/playground'
    | '/policies'
    | '/security'
  id:
    | '__root__'
    | '/'
    | '/agents'
    | '/approvals'
    | '/audit'
    | '/dashboard'
    | '/intents'
    | '/playground'
    | '/policies'
    | '/security'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AgentsRoute: typeof AgentsRoute
  ApprovalsRoute: typeof ApprovalsRoute
  AuditRoute: typeof AuditRoute
  DashboardRoute: typeof DashboardRoute
  IntentsRoute: typeof IntentsRoute
  PlaygroundRoute: typeof PlaygroundRoute
  PoliciesRoute: typeof PoliciesRoute
  SecurityRoute: typeof SecurityRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agents': {
      id: '/agents'
      path: '/agents'
      fullPath: '/agents'
      preLoaderRoute: typeof AgentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/approvals': {
      id: '/approvals'
      path: '/approvals'
      fullPath: '/approvals'
      preLoaderRoute: typeof ApprovalsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/audit': {
      id: '/audit'
      path: '/audit'
      fullPath: '/audit'
      preLoaderRoute: typeof AuditRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/intents': {
      id: '/intents'
      path: '/intents'
      fullPath: '/intents'
      preLoaderRoute: typeof IntentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/playground': {
      id: '/playground'
      path: '/playground'
      fullPath: '/playground'
      preLoaderRoute: typeof PlaygroundRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/policies': {
      id: '/policies'
      path: '/policies'
      fullPath: '/policies'
      preLoaderRoute: typeof PoliciesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/security': {
      id: '/security'
      path: '/security'
      fullPath: '/security'
      preLoaderRoute: typeof SecurityRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AgentsRoute: AgentsRoute,
  ApprovalsRoute: ApprovalsRoute,
  AuditRoute: AuditRoute,
  DashboardRoute: DashboardRoute,
  IntentsRoute: IntentsRoute,
  PlaygroundRoute: PlaygroundRoute,
  PoliciesRoute: PoliciesRoute,
  SecurityRoute: SecurityRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
